### ISSUE TITLE
ui branch crashed when run without network

### ISSUE THREAD

**Issue by 14bird** [jxfn-develop-group/jxfn#1]
/edu.jxfn.jxfn E/AndroidRuntime: FATAL EXCEPTION: main
Process: edu.jxfn.jxfn, PID: 4639
kotlin.KotlinNullPointerException
at edu.jxfn.jxfn.Main$translate$1.invoke(Main.kt:170)
at edu.jxfn.jxfn.Main$translate$1.invoke(Main.kt:30)
at com.github.kittinunf.fuel.core.DeserializableKt$response$2.invoke(Deserializable.kt:37)
at com.github.kittinunf.fuel.core.DeserializableKt$response$2.invoke(Deserializable.kt)
at com.github.kittinunf.fuel.core.DeserializableKt$response$$inlined$apply$lambda$2$1.invoke(Deserializable.kt:69)
at com.github.kittinunf.fuel.core.DeserializableKt$response$$inlined$apply$lambda$2$1.invoke(Deserializable.kt)
at com.github.kittinunf.fuel.core.Request$callback$1.run(Request.kt:205)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5316)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by laxect** [comment]
bug confirm.

**Comment by laxect** [comment]
bug fixed in #https://github.com/jxfn-develop-group/jxfn/commit/ff47cf3bff88381911a8dd35a247775ac477549b
